I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 82, in script
    $pasha_root = pasha_root + 1
  File "game/script.rpy", line 82, in <module>
    $pasha_root = pasha_root + 1
NameError: name 'pasha_root' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 82, in script
    $pasha_root = pasha_root + 1
  File "/home/andrey/soft/RenPy/renpy-6.99.14.3-sdk/renpy/ast.py", line 862, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/andrey/soft/RenPy/renpy-6.99.14.3-sdk/renpy/python.py", line 1888, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 82, in <module>
    $pasha_root = pasha_root + 1
NameError: name 'pasha_root' is not defined

Linux-4.4.0-170-generic-i686-with-debian-stretch-sid
Ren'Py 6.99.14.3.3347
 
Wed Mar 11 14:41:03 2020
